[package]
name = "rust-data-structures-and-algorithms"
version = "0.1.0"
authors = ["binso"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
